### ISSUE TITLE
Component disappears when its content is changed

### ISSUE THREAD

**Issue by piotrsynowiec** [joeattardi/svelte-click-outside#2]
I have a simple component that changes its content when <p> element is clicked. When I click on that element (and change the content of the component) the whole element disappears, because it's treated as an outside element.

`
{#if addNew === 'project'}
<ClickOutside
          on:clickoutside={() => (addNew = null)}
          exclude={[triggerEl]}>

          <div class="box">
            {#if newBox === 'one'}
              <p on:click={() => (newBox = 'two')}>One</p>
            {:else if newBox === 'two'}
              <p>Two</p>
            {/if}
          </div>
</ClickOutside>
{/if}`

**Comment by joeattardi** [comment]
Hmm, I'm not sure exactly how this could work. Normally I would say just add the new content to the `exclude` prop, but if that content doesn't exist at the time then I don't think it would work. The `exclude` prop could be extended to accept CSS selector strings as well, to handle future created elements.

**Comment by joeattardi** [comment]
Closing as this library is no longer maintained.
